#[cfg(feature = "extra")]
pub mod address;
#[cfg(feature = "extra")]
pub mod archive;
#[cfg(feature = "extra")]
pub mod barcode;
#[cfg(feature = "extra")]
pub mod cache;
#[cfg(feature = "extra")]
pub mod clipboard;
#[cfg(feature = "extra")]
pub mod cmd;
#[cfg(feature = "extra")]
pub mod config;
#[cfg(feature = "extra")]
pub mod crypto;
#[cfg(feature = "extra")]
pub mod csv;
#[cfg(feature = "extra")]
pub mod email;
#[cfg(feature = "extra")]
pub mod excel;
#[cfg(feature = "extra")]
pub mod geo;
#[cfg(feature = "extra")]
pub mod html;
#[cfg(feature = "extra")]
pub mod image;
#[cfg(feature = "extra")]
pub mod jwt;
#[cfg(feature = "extra")]
pub mod kv;
#[cfg(feature = "extra")]
pub mod phone;
#[cfg(feature = "extra")]
pub mod pinyin;
#[cfg(feature = "extra")]
pub mod qrcode;
#[cfg(feature = "extra")]
pub mod random;
#[cfg(feature = "extra")]
pub mod template;
