#[cfg(feature = "std")]
pub mod codec;
#[cfg(feature = "std")]
pub mod color;
#[cfg(feature = "std")]
pub mod daterange;
#[cfg(feature = "std")]
pub mod decimal;
#[cfg(feature = "std")]
pub mod desensitize;
#[cfg(feature = "std")]
pub mod diff;
#[cfg(feature = "std")]
pub mod emoji;
#[cfg(feature = "std")]
pub mod file;
#[cfg(feature = "std")]
pub mod filter;
#[cfg(feature = "std")]
pub mod hash;
#[cfg(feature = "std")]
pub mod high_res_timer;
#[cfg(feature = "std")]
pub mod i18n;
#[cfg(feature = "std")]
pub mod id;
#[cfg(feature = "std")]
pub mod json;
#[cfg(feature = "std")]
pub mod list;
#[cfg(feature = "std")]
pub mod map;
#[cfg(feature = "std")]
pub mod money;
#[cfg(feature = "std")]
pub mod net;
#[cfg(feature = "std")]
pub mod regex;
#[cfg(feature = "std")]
pub mod system;
#[cfg(feature = "std")]
pub mod text;
#[cfg(feature = "std")]
pub mod time;
#[cfg(feature = "std")]
pub mod tree;
#[cfg(feature = "std")]
pub mod unit;
#[cfg(feature = "std")]
pub mod url;
#[cfg(feature = "std")]
pub mod validate;
